# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from test_web_001.test_001.test_ren.test_base_001 import Base001

class TestLogin001(Base001):

    def test_login_001(self):
        self.driver.get("https://ceshiren.com/")
        self.driver.maximize_window()
        self.driver.find_element(By.CSS_SELECTOR, ".d-button-label:nth-child(2)").click()
        self.driver.find_element(By.ID, "login-account-name").send_keys("1432519606@qq.com")
        self.driver.find_element(By.ID, "login-account-password").send_keys("143250meimei")
        self.driver.find_element(By.ID, "login-button").click()

if __name__ == "__main__":
    login_001=TestLogin001()
    login_001.test_login_001()

